# Generated by Django 4.0.5 on 2022-07-14 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='uniqueId',
            field=models.CharField(default=datetime.datetime(2022, 7, 14, 15, 42, 48, 961953), max_length=255, unique=True),
        ),
    ]
