# Generated by Django 4.0.5 on 2022-07-14 10:14

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expenseitem_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='uniqueId',
            field=models.CharField(default=builtins.id, max_length=255, unique=True),
        ),
    ]
