# Generated by Django 4.0.5 on 2022-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expenseitem_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='uniqueId',
            field=models.CharField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
