# Generated by Django 4.0.5 on 2022-07-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_expenseitem_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='uniqueId',
        ),
    ]
